meta_product_name: "Sew Far"
meta_type: "website"
meta_title: "Sew Far"
meta_description: "A 2-way marketplace with Stripe payment gateway, AWS S3 integration,
data validation, & authorisation."
meta_image: "screenshot.png" # should exist in `app/assets/images/`
twitter_account: "@drumovski"   # required for Twitter Cards