# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Garment.delete_all
Garment.create([
    { name: 'apron' },
    { name: 'bikni' },
    { name: 'bodysuit' },
    { name: 'braces' },
    { name: 'cardigan' },
    { name: 'chaps' },
    { name: 'chuddah' },
    { name: 'coat' },
    { name: 'codpiece' },
    { name: 'cummerbund' },
    { name: 'dress' },
    { name: 'dressing gown' },
    { name: 'dungarees' },
    { name: 'garter' },
    { name: 'gloves' },
    { name: 'gown' },
    { name: 'halter' },
    { name: 'hat' },
    { name: 'jacket' },
    { name: 'jerkin' },
    { name: 'jubbah' },
    { name: 'jumper' },
    { name: 'jump suit' },
    { name: 'kaftan' },
    { name: 'kimono' },
    { name: 'kilt' },
    { name: 'leotard' },
    { name: 'mask' },
    { name: 'mittens' },
    { name: 'negligee' },
    { name: 'nightgown' },
    { name: 'nightshirt' },
    { name: 'overalls' },
    { name: 'overcoat' },
    { name: 'overskirt' },
    { name: 'pullover' },
    { name: 'pyjamas' },
    { name: 'robe' },
    { name: 'sash' },
    { name: 'sari' },
    { name: 'sarong' },
    { name: 'shalwar' },
    { name: 'shawl' },
    { name: 'shirt' },
    { name: 'shoe' },
    { name: 'shorts' },
    { name: 'skirt' },
    { name: 'skivvy' },
    { name: 'smock' },
    { name: 'socks' },
    { name: 'sweater' },
    { name: 'swimming costume' },
    { name: 'tank top' },
    { name: 'thong' },
    { name: 'tie' },
    { name: 'tights' },
    { name: 'toga' },
    { name: 'T-shirt' },
    { name: 'undergarment' },
    { name: 'waistcoat' },
    { name: 'yashmak' },
])